name: Call automation workflow

on:
  workflow_dispatch:
    inputs:
      central_repository:
        description: "The central repository that should be used."
        required: true
        type: string
      workpackage_id:
        description: "The id of the work package you want to run."
        required: true
        type: string
      filepath:
        description: "MEI file you want to change."
        required: true
        type: string
      parameters:
        description: "Additional parameters required by the work package."
        required: false
        type: string
      workpackage_json:
        description: "The selected work package from the json as a string."
        required: true
        type: string
      commit_message:
        description: "Commit message added by mei-friend or manually when dispatching"
        required: true
        type: string

permissions:
  contents: write

jobs:
  call-shared:
    uses: ${{ inputs.central_repository }}
    with:
      workpackage_id: ${{ github.event.inputs.workpackage_id }}
      filepath: ${{ github.event.inputs.filepath }}
      parameters: ${{ github.event.inputs.parameters }}
      workpackage_json: ${{ github.event.inputs.workpackage_json }}
      commit_message: ${{ github.event.inputs.commit_message }}
